### ISSUE TITLE
Nightly conda builds for development version

### ISSUE THREAD

**Issue by ischoegl** [Cantera/enhancements#24] opened 2020-01-14 18:45 UTC
**Abstract**

Currently, there often is a significant lag between the development version and packages available on conda. 

**Motivation**

As an effect, bug fixes (or new features) are not available to the community unless they build Cantera from source, which may be a non-trivial endeavor (e.g. Windows).

**Possible Solutions**

Check for new GH commits to master (i.e. newly merged PR's) once a day, and trigger a new build when necessary (this assumes that the conda-recipes CI services are scriptable).

**Comment by bryanwweber** [comment] 2020-07-06 13:41
Any reason to close this? With the transition to GH Actions I think this will actually be significantly easier.

**Comment by ischoegl** [comment] 2020-07-06 14:36
> Any reason to close this? 

Just thought that it wasn't worth keeping all those issues open.

**Comment by bryanwweber** [comment] 2021-04-05 13:45
@ischoegl I'm going to close this as a duplicate of #37, if you disagree feel free to reopen

**Closed by bryanwweber** 2021-04-05 13:45 UTC
Labels: feature-request

**Comment by ischoegl** [comment] 2021-04-05 14:33
@bryanwweber ... no problem. I believe this request predates #37, and it’s ok if this is ‘superseded’.
