### ISSUE TITLE
Physics-Informed Machine Learning in Cantera

### ISSUE THREAD

**Issue by jiweiqi** [Cantera/enhancements#82] opened 2021-02-21 16:14 UTC
**Abstract**

Physics-Informed Machine Learning is a hot topic these days initialized by the success of deep learning in computer visions and natural language programming. While this is a pretty new journey and it is too early to say what it will be, quite a lot of physics-informed machine learning is in the categories of augmenting physics models into neural network models. To name a few, [physics-informed neural networks](https://science.sciencemag.org/content/367/6481/1026.abstract?casa_token=KZ43PXYHMEsAAAAA:bChUteoCLbNfZ5kE18LnpVr0WFpERuaRHho6xNvJymjkln0e-ng8OQ3JNOHMdj99vm2G5rCt1xgblcE), [neural ordinary differential equations](https://arxiv.org/abs/1806.07366). To us, it is the chemical kinetic models.

**Motivation**

The infrastructure that those physics-informed machine learning need can be summarized as

* Auto-differentiation over the reaction source term.
* Tensor operation for batch evaluation. For example, evaluate the reaction source term in a flame (1/2/3-d) in a single pass.
* GPU support for training.
* Coupling with model deep learning framework TensorFlow and PyTorch

**Possible Solutions**

**Extend Cantera to support those features**

* Auto-differentiation over the reaction source term.
* Coupling with model deep learning framework TensorFlow and PyTorch.
* Tensor operation for batch evaluation. For example, evaluate the reaction source term in a flame (1/2/3-d) in a single pass.
* GPU support for training.

**Build a new `Cantera` in those deep learning frameworks**, some initiatives are

* [ReacTorch](https://github.com/DENG-MIT/reactorch) in PyTorch
* [Arrhenius.jl](https://github.com/DENG-MIT/Arrhenius.jl) in Julia
* [ReactionMechanismSimulator.jl](https://github.com/ReactionMechanismGenerator/ReactionMechanismSimulator.jl) in Julia

**References**

* Auto-differentiation over the reaction source term. #80 
* ReacTorch in PyTorch #49 
* Julia support in Cantera #81 #39 
* [Example of hybrid neural networks with existing chemical kinetic models by Arrhenius.jl](https://github.com/DENG-MIT/CRNN_HyChem/blob/15cd93cbb23cb264cd6eb9d44b4c533a37e1294b/network.jl#L44). Basically add wdot from kinetic model and wdot from neural networks and train the neural network using neural ordinary differential equations.

Due to the limitation of my knowledge, I definitely have missed some important or promising ML directions for combustion here. For example reinforcement learning, variational inference, GAN and various of reduced-order modeling frameworks. Feel free to add so that we could invest our limited time in the most promising development.

**Comment by bryanwweber** [comment] 2021-04-05 13:32
@jiweiqi I'm going to close this as a duplicate of #80 and #81. Please feel free to add a comment and reopen if you feel it is worth keeping open. Thanks!

**Closed by bryanwweber** 2021-04-05 13:32 UTC
Labels: feature-request

**Comment by jiweiqi** [comment] 2021-04-05 14:00
@bryanwweber Thanks for your maintance. I also think, the current short-term technical requirement is enhancing Julia's interface, which can be discussed in #81.
